Manual fix ruff
troyvvgroup/quemb pull request #49
Opened 2024-12-09 19:10 UTC by mcocdawc

Fixed remaining errors in `src/quemb/shared/external/cpmp2_utils.py` and `src/quemb/molbe/solver.py` 

- removed unused variables
- made it explicit that `update_heff` modifies self, i.e. it returns nothing now.
- removed `ecore` from everywhere. It did not do anything anyway. If it should be reintroduced it is much easier, if automatic code analysis (unused arguments in particular) works.

part of #44

2024-12-09 20:42 UTC, mscho527 commented
> * removed `ecore` from everywhere. It did not do anything anyway. If it should be reintroduced it is much easier, if automatic code analysis (unused arguments in particular) works.

It looks like functionality related to frozen core was stripped down here; we should perhaps discuss how to proceed with this.

2024-12-09 23:26 UTC, mcocdawc commented
> > * removed `ecore` from everywhere. It did not do anything anyway. If it should be reintroduced it is much easier, if automatic code analysis (unused arguments in particular) works.
> 
> It looks like functionality related to frozen core was stripped down here; we should perhaps discuss how to proceed with this.

the functionality does not exist. There is an `ecore` argument to the outside, but that is never used. I would rather explicitly remove it and then cleanly add it, than have a non-working argument.

2024-12-10 17:13 UTC, mscho527 commented on src/quemb/molbe/solver.py
> +            h1, _ = cas.get_h1eff(mo_coeff=fobj._mf.mo_coeff)
```suggestion
            h1, _ = cas.get_h1eff(mo_coeff=fobj._mf.mo_coeff)  # h1, ecore
```

2024-12-10 17:13 UTC, mscho527 commented on src/quemb/molbe/solver.py
> -        heff_ = None  # No outside chemical potential implemented for unrestricted yet
we probably want to create an issue @lweisburn

2024-12-10 17:15 UTC, mscho527 requested changes
mostly cool, i think a few comments would be nice!

2024-12-10 19:34 UTC, mscho527 approved these changes

2024-12-10 19:56 UTC, merged