More type annotations + simpler boolean expressions
troyvvgroup/quemb pull request #76
Opened 2024-12-23 17:32 UTC by mcocdawc

Only review after #74 is merged

A couple more type annotations and simpler boolean expressions

2025-01-08 19:23 UTC, mscho527 commented on src/quemb/kbe/lo.py
> +                    Ciao_[k] = ctmp
As the comment suggests, reordering might be unnecessary. Verify this when dealing with #60

2025-01-08 19:58 UTC, mscho527 commented on src/quemb/molbe/misc.py
>                  )
```suggestion
                if not use_df or not jk:
                    raise ValueError(
                        "Setting use_df to false and jk to none: have not tested DF and "
                        "QM/MM from point charges at the same time"
                    )
```

2025-01-08 19:59 UTC, mscho527 commented on src/quemb/molbe/misc.py
>                  )
When `use_df` is False and `jk` is None, we want QM/MM to run

2025-01-08 20:34 UTC, mscho527 requested changes
Looks good otherwise!

2025-01-09 00:04 UTC, mcocdawc commented on src/quemb/kbe/lo.py
> +                    Ciao_[k] = ctmp
but for the moment I leave it it as is?

2025-01-09 00:12 UTC, mcocdawc commented on src/quemb/molbe/misc.py
>                  )
your change is different from what you are saying in words.
```python3
if not use_df and jk is None:
    # run
```
becomes
```python3
if not (not use_df and jk is None):
    # raise error
```
becomes
```python3
if use_df or jk is not None:
    # raise error
```

what do we want?

2025-01-09 00:15 UTC, mscho527 commented on src/quemb/kbe/lo.py
> +                    Ciao_[k] = ctmp
yes yes! Sorry should've been clearer :)

2025-01-09 00:18 UTC, mscho527 commented on src/quemb/molbe/misc.py
>                  )
The last code block would do! I didn't notice this before, but I suppose this input validity check & exception should happen before actually doing the mf calculations.

2025-01-09 16:59 UTC, mcocdawc commented on src/quemb/molbe/misc.py
>                  )
thank you and done

2025-01-09 17:12 UTC, mscho527 approved these changes
cool cool coool niice

2025-01-09 17:29 UTC, mscho527 requested changes
@mcocdawc leah has a comment that we should probably consider before merging pr; un-approving this for now

2025-01-09 18:01 UTC, mcocdawc commented
> @mcocdawc leah has a comment that we should probably consider before merging pr; un-approving this for now

oh yeah, I wanted to ask for her review anyway due to my merge conflicts with her changes.

2025-01-09 18:06 UTC, lweisburn commented
I had a comment about `return_rdm`, per a discussion with @mscho527, that I want to rescind! The current logic in `be_parallel` makes sense to me wrt to the rdm returns and relaxed/unrelaxed densities. I think that in the future, if we add something to the code such that we do not need the energy and/or the rdms at each iteration, we will have to make some changes, but this makes sense for now!

2025-01-09 18:16 UTC, lweisburn commented on src/quemb/molbe/lo.py
> +    return cano_orth(Cpao, ovlp=S)
I think this could be misleading: get_pao is returning a function of Cpao (which we really want to be calling cpao). Instead, maybe we call Cpao in line 173 Cpao_redundant or something? Cpao should be refering to the canonically orthogonalized version

2025-01-09 18:21 UTC, lweisburn commented on src/quemb/molbe/solver.py
> +                ucc, relax=relax, with_dm1=with_dm1 and not use_cumulant
This logic should be the same as above: `with_dm1` is True if `use_cumulant` is false, a separate `with_dm1` is unnecessary

2025-01-09 18:25 UTC, mcocdawc commented on src/quemb/molbe/lo.py
> +    return cano_orth(Cpao, ovlp=S)
that's an easy change. done

2025-01-09 18:30 UTC, mcocdawc commented on src/quemb/molbe/solver.py
> +                ucc, relax=relax, with_dm1=with_dm1 and not use_cumulant
Note that `with_dm1` is also an argument to the function.

Before it was
```
if use_cumulant:
                with_dm1 = False
```
in particular it was **not**
```
with_dm1 = True
if use_cumulant:
                with_dm1 = False
```
as in other similar cases (which would allow your requested change to be fully equivalent)

My current change is exactly equivalent to the previous behaviour.


I can easily change to use only  `use_cumulant`, but then I will also remove the `with_dm1` argument

2025-01-09 18:36 UTC, lweisburn commented on src/quemb/molbe/solver.py
> +                ucc, relax=relax, with_dm1=with_dm1 and not use_cumulant
Yes, you're exactly right in the way you did this! I would just remove the `with_dm1` argument altogether, it's inherently redundant. You will never want the density generated with `with_dm1`True if you are running the code requesting the cumulant energy. Thank you for fixing/clarifying the redundancy in the current logic

2025-01-09 18:44 UTC, mcocdawc commented on src/quemb/molbe/solver.py
> +                ucc, relax=relax, with_dm1=with_dm1 and not use_cumulant
done :)

2025-01-09 19:52 UTC, lweisburn commented on src/quemb/molbe/be_parallel.py
>              raise NotImplementedError("RDM Return not Implemented")
This is no longer the right error: I don't think we need an "else" error anymore. This should just be building the rdm2s when we have the unrelaxed density.

2025-01-09 19:53 UTC, lweisburn commented on src/quemb/molbe/be_parallel.py
>              raise NotImplementedError("RDM Return not Implemented")
Everything looks good to me otherwise!!

2025-01-09 20:20 UTC, lweisburn approved these changes
It looks good to me!!

2025-01-09 20:25 UTC, merged